more

diff --git a/no-stderr b/no-stderr
--- a/no-stderr
+++ b/no-stderr
@@ -1,3 +1,6 @@
 #!/bin/bash -ie
 
 "$@" 2>&1
+if $? != 0 ; then
+    echo "command failed $?" >&2
+fi
